---
title: '[En] Monkeypox'
author: H
date: '2023-05-12'
categories: [En]
tags:
  - Nature
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Resource:

[**The disease will be neglected: scientists react to WHO ending mpox emergency**](https://www.nature.com/articles/d41586-023-01581-1)


Monkeypox has been removed from the list of global emergencies by the WHO. This decision was made based on the decline in cases over the past three months. However, this infectious disease is still prevalent in African regions where vaccines and therapeutics are difficult to access. Other experts are concerned that cases may surge due to upcoming summer events. Additionally, the removal of priority status may divert research resources away from addressing critical unanswered questions about the virus, such as its transmission between populations. Unfortunately, there are other diseases that require more attention globally, highlighting wealth inequality between countries. 


## Vocabulary 

**curbing** the outbreak: restrain <br>
the resources will **dwindle**: diminish <br>
**galvanize** support: stimulate <br>
