---
title: '[En] Dopamine levels'
author: H
date: '2023-03-29'
categories: [En]
tags:
  - Podcast
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Resource:

[**Leverage Dopamine to Overcome Procrastination & Optimize Effort**](https://podcasts.apple.com/gb/podcast/huberman-lab/id1545953110?i=1000606049488)


The level of dopamine has a strong relationship with motivation and desires. There are mainly 5 dopamine circuits in the brain. VTA is relevant to motivation. For example, desires trigger the peak of dopamine and initiate the action to satisfy the desires. Once the desires are fulfilled, the crash of dopamine occurs. This circuit learns how to achieve the desires subconsciously and predicts the effort involved in the action the next time. In drug addiction, for example, the time between the peak and crash of dopamine is short, which means the desires can be fulfilled quickly and give the circuit extremely positive feedback. In order to maintain the dopamine levels, we can follow the suggestions below:

Get sufficient sleep (restoring the baseline of dopamine), try Yoga Nidra
Eat foods that increase dopamine, such as dark vegetables
Get morning sunlight early in the day (for 10-20 minutes), to boost cortisone levels.






