---
title: '[En] Primate embryo'
author: H
date: '2023-05-14'
categories: [En]
tags:
  - Nature
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Resource:

[**Lab-grown monkey embryos reveal in 3D how organs begin**](https://www.nature.com/articles/d41586-023-01544-6)


There has been a breakthrough in developmental biology. Scientists have successfully cultured primate embryos outside the uterus for 25 days. Previously, the longest duration embryos could be kept in a laboratory setting was 20 days, during which the embryos were merely bags of cells in the disc and would collapse afterward.

With advancements in methods, embryos are now kept in cylindrical containers to mimic the environment in the womb. This allows for the observation of the three layers, the endoderm, mesoderm and ectoderm, that form during early development, as well as differentiated cells such as nerves and blood cells. While there is still room for improvement to make it applicable in real experiments, this achievement marks a significant milestone in the field of developmental biology.



## Vocabulary 

**coaxed** their embryos: obtain something from (someone) by gentle and persistent persuation <br>




