---
title: '[En] The signs of life in space'
author: H
date: '2023-05-19'
categories: [En]
tags:
  - Nature
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Resource:

[**JWST spots biggest water plume yet spewing from a moon of Saturn**](https://www.nature.com/articles/d41586-023-01666-x)

The James Webb Space Telescope has only been in orbit for a year, yet it has already played a key role in space exploration. It is located near Earth's orbit but can provide more information about Enceladus, a moon of Saturn, than the Cassini spacecraft, which is closer to Saturn. Scientists have discovered possible signs of life on Enceladus, including a plume of icy water spraying from its surface and containing silica, which may originate from the churning of its icy bottom. These findings were spotted by the JWST in just a few minutes. There is much more to expect from the future of the JWST


## Vocabulary 

**spurting** from: gush out <br>
**spewing** from: expel large quanitities quickly <br>
look for **extraterrestrial** life: outspace <br>
**churning** fluid: stir <br>
too **sparse** to detect: too little <br>
**habitability** <br>
provide **grist** for: usefull material  <br>




